version: '3.8'
services:
  react-app:
    image: node:14-alpine
    volumes:
      - ./:/react-three
    ports:
      - "3000:3000"
    restart: always
    command: sh -c "cd react-three && npm install && npm run dev"
